- hosts: all
  become: yes
  tasks:
    - name: copy to '/etc/login.defs'
      copy:
        src: ./files/login.defs
        dest: /etc/login.defs
        owner: root
        group: root
        mode: '0644'
